spring:
  application:
    name: XLinkSnap
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: unkonwnzz
    url: jdbc:mysql://localhost:3306/xlinksnap?characterEncoding=utf-8&useSSL=false
  cache:
    type: redis
  redis:
    database: 0
    port: 6379
    host: 192.168.94.130
    timeout: 5000
server:
  port: 8081

mybatis-plus:
  mapper-locations: classpath:com/wz/xlinksnap/mapper/xml/*.xml