spring:
  application:
    name: XLinkSnapGateWay
  cloud:
    gateway:
      routes:
        - id : xlinksnap01
          uri : http://localhost:8081
          predicates:
            - Path=/api/**
server:
  port: 8200

